[workspace]
members = [
    "crates/data-check/expiry", 
    "crates/data-check/integrity", 
    "crates/sig-check/dsc", 
    "crates/sig-check/passport-data",
    "crates/proof/age",
    "crates/proof/citizenship",
]
