[workspace]
members = [
    "crates/bin/data-check/expiry", 
    "crates/bin/data-check/integrity", 
    "crates/bin/sig-check/dsc", 
    "crates/bin/sig-check/passport-data",
    "crates/bin/proof/age",
    "crates/bin/proof/citizenship",
    "crates/bin/combined/age",
]
