[package]
name = "proof_age"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
proof_age = { path = "../../../lib/proof/age" }
utils = { path = "../../../lib/utils" }