[package]
name = "sig_check_dsc"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
rsa = { tag = "main", git = "https://github.com/madztheo/noir-rsa-optimised", directory = "crates/rsa" }
large_integer = { tag = "main", git = "https://github.com/madztheo/noir-large-integer", directory = "crates/large-integer-64" }
utils = { path = "../../utils" }